export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILD = 'LOGIN_FAILD'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const SUIT_FETCH_START = 'SUIT_FETCH_START'
export const SUIT_FETCH_SUCCESS = 'SUIT_FETCH_SUCCESS'
export const SUIT_FETCH_FAILD = 'SUIT_FETCH_FAILD'
